# -*- coding: utf-8 -*-
"""
/***************************************************************************
 geocode_aspb
                                 A QGIS plugin
 Importa capas i calcular similituds
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-05-30
        copyright            : (C) 2024 by PSIG
        email                : paust2001@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load geocode_aspb class from file geocode_aspb.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .geocode_aspb import geocode_aspb
    return geocode_aspb(iface)
